#!/bin/sh
# by Dominik Stanisław Suchora <suchora.dominik7@gmail.com>
# License: GNU GPLv3

if [ "$1" = '-h' ]
then
    printf "%s DIR\ndownload stories from sexstories.com\n" "$(basename "$0")"
    exit 0
fi

OUTDIR="."
[ "$#" -gt 0 ] && OUTDIR="$1"
cd "$OUTDIR" || exit 1

DOMAIN="https://sexstories.com"
alias ucurl='curl -k -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/87.0.4280.144 Safari/537.36" -H "Accept-Encoding: gzip, deflate" --compressed'

for i in $(seq `ucurl -s "$DOMAIN/updates/" | reliq 'div .pager; a [-] | "%(href)v\n" / sed "s#.*/##;q"'`)
do
    for j in $(ucurl -s "$DOMAIN/updates/$i" | reliq 'h4; a href=b>"/story/" | "'$DOMAIN'%(href)v\n"')
    do
        #[ "$(jobs | wc -l)" -gt '8' ] && wait -n
        #{
        t="$(ucurl -s "$j")"
        NAME="$(echo "$t" | reliq 'div .story_info; h2 | "%i" / tr "\n" sed "s/<.*//;s/ *$//"' | recode html..UTF-8)"
        FNAME="$(echo "$NAME" | sed 's/\//|/g')"
        AUTHOR="$(echo "$t" | reliq 'div .story_info; h2; a | "%i\n" / sed "/^$/s/^/Anonymous/"' | recode html..UTF-8)"
        GENRES="$(echo "$t" | reliq 'div .top_info | "%i\n" / line [0]')"
        TIME="$(echo "$t" | reliq 'div .story_date | "%i\n" / sed "s/ *<.*//"')"
        COMMENTS="$(echo "$t" | reliq 'div .count_comments | "%i\n"')"
        READ="$(echo "$t" | reliq 'div .block_panel; div .story_info | "%i\n" / sed "/^Read/{s/<span.*\">//; s/<\/span>//; s/ |$//;p}" "n"')"
        RATED="$(echo "$t" | reliq 'div .block_panel; div .story_info | "%i\n" / sed "/Rated/{s/<span.*\">//; s/<\/span>//; s/ |$//; s/ %/%/; s/^ *//;p}" "n"')"
        VOTES="$(echo "$t" | reliq 'div .block_panel; div .story_info; a .color2 | "%i\n"')"

        printf 'Link: "%s"\nTitle: "%s"\nAuthor: "%s"\nGenres: "%s"\nTime: "%s"\nRead: "%s"\nRated: "%s"\nVotes: "%s"\nComments: "%s"\n\n' "$j" "$NAME" "$AUTHOR" "$GENRES" "$TIME" "$READ" "$RATED" "$VOTES" "$COMMENTS" > "$FNAME"
        echo "$t" | reliq 'div .block_panel | "%i\n"' | sed '/<!-- VOTES -->/q' | sed -E '/<!-- VOTES -->/d; s/ {2,}//g; s/<h2>//; s/<\/h2>//; s/<br \/>//g; s/\r//g' | recode html..UTF-8 >> "$FNAME"
        echo "$FNAME"
        #} &
    done
done
